### ISSUE TITLE
Weird route taken around crossroads by bike

### ISSUE THREAD

**Issue by AlbertJP** [valhalla/sif#120]
This is quite a weird route for cyclists around the crossroads of Constant Erzeijstraat and 't Goylaan, Utrecht, Netherlands.
The parallel road of 't Goylaan (ie the road below the hairdresser icon) has a oneway:bicycle=no tag.

![route](https://cloud.githubusercontent.com/assets/1248033/16045854/9a92326e-324a-11e6-9991-5fc9a05c1c67.png)

(There's currently roadworks in the area, but that hasn't been mapped on OSM so far.)

**Comment by dnesbitt61** [comment]
We can route west to east on 't Goylaan. This is triggering the maneuver penalty (defaults to 10 seconds) when turning onto 't Goylaan and then again when getting back onto the cycleway.

**Comment by dnesbitt61** [comment]
Looks like 2 things need to be adjusted: 1) stop impact is reduced when going from cycleway to cycleway which means the cost of crossing the secondary roads in this example is too low, and 2) maneuver penalty is too high.  Will test some changes and see if these adjustments do not cause side effects.

**Comment by AlbertJP** [comment]
I've got more examples where a too high penalty is associated with the usage of residential roads, even if the road is a parallel road which is de facto a cycle route with an occasional car (just like this one).
https://www.openstreetmap.org/directions?engine=mapzen_bicycle&route=52.0668%2C5.1164%3B52.0747%2C5.1135 using Jutphaseweg (1.2km)
https://www.openstreetmap.org/directions?engine=graphhopper_bicycle&route=52.0668%2C5.1164%3B52.0747%2C5.1135 using Rijnlaan (1.0km)

While GraphHopper seems to implement no turn penalties at all, leading to complicated routes, in this case its route makes more sense.

**Comment by dnesbitt61** [comment]
Initial route is fixed in latest release. Other examples are TBD - the last example is a difference of 0.1km so I'm not sure how critical this is? We have reduced some of the penalties and favoring of cycleways by default, but need to keep some turn penalties in place to prevent extraneous maneuvers.
