### ISSUE TITLE
Cost of right-hand turns in Left-Hand-Drive country?

### ISSUE THREAD

**Issue by quilkin** [valhalla/sif#125]
There is a small extra 'loop' in a local main road (now just a  lay-by  or parking area where the new road has been straightened) which is used by the routing engine when mountain or hybrid bike types are used. That's sort of understandable if the extra loop is on the same side as the direction of travel (although in practice I doubt any rider would take the loop) but _not_ if one has to cross the main road to use it.

The routing engine, however, _only_ uses the loop _if it is necessary to cross the main road_. It appears that the algorithm to detect turns across busy roads thinks this road is in a right-hand-drive country. But the system knows we are left-hand drive because roundabouts are tackled correctly.
I tried to include a screenshot here but failed, sorry. The road in the example is at approx 50.2997, -4.91132, and I have set use_roads to max (1.0), but I assume the same will be happening with other similar loops off  main roads.

**Comment by dnesbitt61** [comment]
Thanks - we will look at this further. I seem to only get this with use_roads set to 0.5. Is this the basic area/route? I get this behavior going in either direction (agree it is an issue!).

![screenshot from 2016-08-01 12 06 44](https://cloud.githubusercontent.com/assets/1838768/17300452/7446782a-57e0-11e6-99c3-6e0a1536d4f2.png)

**Comment by quilkin** [comment]
Yes - that's the correct location for my example.
I just tried again with use_roads at 1.0 and bike=hybrid. Going W-E it 
doesn't use the minor loop; returning it does.
But whatever bike (and whatever choice of main road use?) ideally it 
shouldn't be necessary to cross a road twice to use a 100-metre section 
of alternative.

Thanks
Chris

**Comment by dnesbitt61** [comment]
Fixed with latest release.
