### ISSUE TITLE
Problems at crossing in Utrecht - for bike and foot

### ISSUE THREAD

**Issue by AlbertJP** [valhalla/sif#148]
Hello,

It appears routing over [this crossing](http://www.openstreetmap.org/node/45216221) is causing some problems.

[Cycling](https://www.openstreetmap.org/directions?engine=mapzen_bicycle&route=52.09353%2C5.11871%3B52.09371%2C5.11884) lets me make five turns around the place, instead of just one left turn.
[Walking](https://www.openstreetmap.org/directions?engine=mapzen_foot&route=52.09353%2C5.11871%3B52.09371%2C5.11884) involves a U-turn because it seems impossible to go straight on at [this junction of two cyclepaths](http://www.openstreetmap.org/node/2902619187).

Screenshots of current routes, by bike and foot:
![screenshot from 2016-10-11 22 23 03](https://cloud.githubusercontent.com/assets/1248033/19287331/995ef6ba-9001-11e6-898c-c8e6e8464113.png)
![screenshot from 2016-10-11 22 24 52](https://cloud.githubusercontent.com/assets/1248033/19287342/a48623a6-9001-11e6-9ec5-573af95c9ce2.png)

**Comment by gknisely** [comment]
Thank you so much for sending us this issue.  We will look at this as soon as we can get to it.  Have a great day!

**Comment by dnesbitt61** [comment]
Looks like this way http://www.openstreetmap.org/way/7057508 has access=destination which applies a penalty in our routing (to avoid taking roads that allow access only when the destination is along the way or in the area. This penalty prevents routes from cutting through neighborhoods marked as private or destination only (no through routes). Is this marked properly? Perhaps bicycle=yes and foot=yes should override the access=destination for those modes?

**Comment by AlbertJP** [comment]
Should indeed be overridden by bicycle=yes and foot=yes.

**Comment by dnesbitt61** [comment]
Fixed with our latest release, Valhalla 2.0. Thanks for reporting this issue. The bicycle route was due to destination access only penalties and the pedestrian route was due to the road crossing penalty (less cost to go left, make u-turn, then go left again on very short segment).
