### ISSUE TITLE
Driving allows access=hov by default

### ISSUE THREAD

**Issue by ericrwolfe** [valhalla/sif#154]
Noticed on a test drive through Los Angeles that valhalla allows HOV/carpool lane access by default. This should be able to be toggled or weighted as a parameter, but avoided by default.

As a example: 
http://valhalla.github.io/demos/routing/#loc=13,33.679640,-117.850428&locations=[{"lat":33.70849921909863,"lon":-117.85585641860962},{"lat":33.67517567210501,"lon":-117.84549236297607}]&costing="auto"
Maneuver 4 "Take the I 405 exit on the left" routes drivers left onto a separate HOV interchange ramp rather than the normal ramp on the right. The ramp preferred by valhalla is [tagged access=hov](https://www.openstreetmap.org/edit#map=18/33.68864/-117.86885)

**Comment by dnesbitt61** [comment]
Should assing HOV only to not allow car, truck, etc. by default. Only HOV and bus(?). Can then create an HOV costing method, derived from auto to check for HOV access.

**Comment by gknisely** [comment]
Fixed.  Added HOV costing method.
