### ISSUE TITLE
Bike routing should take the Liberty Landing Ferry

### ISSUE THREAD

**Issue by gknisely** [valhalla/sif#73]
Liberty Landing Ferry is a pedestrian and bike only ferry.   It is also part of a bike network.  Currently, the route goes up to George Washington Bridge, which is way out of the users way.

![image](https://cloud.githubusercontent.com/assets/2676277/11149079/b2a88f9c-89ee-11e5-817a-7cd769be39dd.png)

**Comment by dnesbitt61** [comment]
Looks like the default surface type for a footway is kPath - this is excluded by all bikes. Perhaps this should be set to kCompacted by default to allow all bikes (though road bikes will be penalized a bit).

**Comment by dnesbitt61** [comment]
Changing default surface type to kCompacted for footway fixes this issue (fix was in mjolnir).
