### ISSUE TITLE
Border Crossing

### ISSUE THREAD

**Issue by dnesbitt61** [valhalla/sif#81]
http://valhalla.dev.mapzen.com/route?json={%22locations%22:[{%22lat%22:47.56172247383757,%22lon%22:7.545120120266801,%22type%22:%22break%22},{%22lat%22:47.56209894058258,%22lon%22:7.548606991986162,%22type%22:%22break%22}],%22costing%22:%22auto%22}&api_key=valhalla-t_16n1c

In this example, we avoid the border crossing and take a gravel track that has auto access.  :-)

**Comment by gknisely** [comment]
see #82
