### ISSUE TITLE
Wrong cycle route at crossing, direct path avoided probably because it involves more turns

### ISSUE THREAD

**Issue by AlbertJP** [valhalla/sif#88]
(I do not know if this is the right section to post the bug)

At the crossing of Catharijnesingel and Bleekstraat (http://www.openstreetmap.org/#map=19/52.08029/5.12190), a turn left by bike coming from the south involves crossing the Catharijnesingel using way http://www.openstreetmap.org/way/93710713.

But the route I get is the following:
![schermafdruk van 2016-01-16 14 14 13](https://cloud.githubusercontent.com/assets/1248033/12372536/436a5552-bc5c-11e5-86fa-3a2e899ca77f.png)
It makes a U-turn at the place where the cycle path rejoins the road, instead of crossing at the traffic lights.

I pass this place by bike at least once a week, so I know from my own experience that the U-turn would be a very bad idea because the road is usually busy.

**Comment by gknisely** [comment]
Thank you Albert.  We will take a look at it as soon as we can.

--Greg.

**Comment by gknisely** [comment]
@AlbertJP this issue has been fixed and pushed to our servers.  Again, thank you so much for reporting this issue.  Let us know if you have any other problems. 

Thanks.
  --Greg.

**Comment by AlbertJP** [comment]
It was fixed but this issue has recently returned.

**Comment by gknisely** [comment]
Ok.  I think they latest update may have caused this issue to return.  We
will look into it.

Thank you for reporting it.

--Greg.

**Comment by dnesbitt61** [comment]
This is fixed (again).
