### ISSUE TITLE
Bicycle routes avoid roads too much

### ISSUE THREAD

**Issue by AlbertJP** [valhalla/sif#95]
For a route from 52.0993, 5.1422 to 52.10298, 5.13455, the cycle path along the Kardinaal Alfrinkplein roundabout is preferred:
![schermafdruk van 2016-02-07 12 56 57](https://cloud.githubusercontent.com/assets/1248033/12872147/4c18381e-cd9a-11e5-83df-a4ce0dd239e7.png)
However, almost all cyclists taking this route on a daily basis (a lot of university students who live in Zuilen or Overvecht), use the obviously shorter route via the Huizingalaan:
![schermafdruk van 2016-02-07 12 58 29](https://cloud.githubusercontent.com/assets/1248033/12872154/95aa9878-cd9a-11e5-93c8-7d782d0f81f2.png)
Setting the use roads factor to 0.9 routes me this way.
In Utrecht, there are many residential roads which are de facto a cycle route with an occasional car on them. Admittedly, these roads are often tagged as unclassified but that can be changed as residential is the correct tag for them according to the OSM wiki. In my opinion, it is unnecessary to avoid any residential road when routing. This would include any road with one of the following tags:
- highway=residential
- highway=living_street

On roads where cars are driving faster, I understand very well that cyclists may want to avoid them and use cycle paths indeed, if present. For unclassified or higher class roads, the present situation is probably fine.

Furthermore, I think any road bearing one or more of the following tags should not be avoided either because I think these tags make clear that cyclists are supposed to use the roads:
- bicycle=designated
- cycleway=cyclestreet
- bicycle_road=yes

(Good example: Troelstralaan and Merelstraat, Utrecht)

**Comment by dnesbitt61** [comment]
We will look at this a bit. Cycleways are favored, but maybe we favor them too much over lower speed, lower classed roadways. We favor roads with bike lanes or that are part of a bicycle network (relation) but will also look at these tags to see how we represent them.

**Comment by gknisely** [comment]
@AlbertJP shouldn't Troelstralaan and Merelstraat be marked with motor_vehicle=yes as well?  Based on the wiki (http://wiki.openstreetmap.org/wiki/Key:bicycle_road) bicycle_road implies vehicle=no.  

Also, please note that the wiki says that this is only for Germany, which I don't believe is the case.  Can you confirm?

From the wiki:
These kind of roads get more and more common in Europe. So far, this page is about the situation in Germany.

Again, thank you for your time. 

  --Greg

**Comment by gknisely** [comment]
@AlbertJP Did you have a minute to look at my previous response?  

Thanks.  

  --Greg.

**Comment by AlbertJP** [comment]
@gknisely I'm sorry. The Troelstralaan and Merelstraat should indeed have vehicles allowed.
The roads which we call "fietsstraat" in Dutch allow cars, but cyclists have priority. There seems to be no real concensus on how to tag them. Some use cycleway=cyclestreet but this tag is hardly documented.

**Comment by dnesbitt61** [comment]
We updated bicycle routing. We still take the cycleway but have reduced how much cycleways are favored vs. surface streets, it will take your preferred route at a lower value of use_roads. We've received some conflicting requests - some folks want to favor cycleways more and some want to favor them less. We're trying to hit a middle ground and tune the use_roads factor to allow different preferences. It is a bit tricky! If you want to re-open a new issue feel free.
